sudo: required
services:
  - docker

before_install:
  - docker build -t mivaldiv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mivaldiv/react-test npm test

after_success:
  - docker build -t mivaldivia/multi-client ./client
  - docker build -t mivaldivia/multi-nginx ./nginx
  - docker build -t mivaldivia/multi-server ./server
  - docker build -t mivaldivia/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mivaldivia/multi-client
  - docker push mivaldivia/multi-nginx
  - docker push mivaldivia/multi-server
  - docker push mivaldivia/multi-worker

deploy:
  provider: elastickbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-576946215109
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCES_KEY
  secret_access_key: $AWS_SECRET_KEY
